# ===========================================
# Information Settings
# ===========================================

#navigation
menu: 
  #article: /
  archives: /archives
  categories: /categories
  tags: /tags
  about: /about
  #RSS: /atom.xml

# favicon
favicon: 

# ===========================================
# Color&Schemes Setting
# ===========================================

## Common

# Mobile-Header
# light | dark
mobile-header: light

# Scheme
# banderole | balance
scheme: banderole

## Banderole
# Header Style
# line | block
header-style: block

# Article Header Sign
header_sign: ∮

# theme-style
# miku | sakura | dark | green | blue | purple
theme-style: blue

# ===========================================
# Article Setting
# ===========================================

# Navigator in post
toc: true

# Use copyright infomation
copyright:
  enable: true
  # license: 

#Reword button or message(fill your QRCode of any Pay.)
reward:
  enable: false
  # message:
  qrcode:
    # alipay:
    # wechat:
    # paypal:

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments: 
  enable: true

  # disqus: 
  # livere_datauid:

  # changyan:
  #   appid: 
  #   appkey: 

  # gitment:
  #   owner:
  #   repo:
  #   client_id:
  #   client_secret:

# sub //Please just fill out ID.
sub:
  github: 3ylh3

#Friend link
# friendLink:

# ===========================================
# Analytics
# ===========================================

analytics:
  google:
  baidu:

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: true

# ===========================================
# Theme Settings
# ===========================================

# mathjax
mathjax: true

# lightbox
lightbox: true

# lazyload
lazyload: false

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# Created Time
since: 2019

# plugin
# plugins:

# about
# self:  

# ===========================================
# Search Settings
# ===========================================

# Search 
search:
  enable: true
  label: 搜索一下？

# ===========================================
# Documents Styles
# ===========================================

# article-fonts
# default | Simsun | YaHei | Hel | Custom
fonts-style: default

# code-fonts
# default | Custom
code-style: default

# ===========================================
# WebApp Settings (iOS)
# ===========================================


# ===========================================
# Version
# ===========================================
version: 2.4

#theme_author: Co1MugX
